"""initial

Revision ID: fb166b2c1092
Revises:
Create Date: 2026-07-19 10:51:50.534810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'fb166b2c1092'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_hr_candidate',
    sa.Column('candidate_no', sa.VARCHAR(length=32), nullable=False),
    sa.Column('candidate_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('mobile', sa.VARCHAR(length=20), nullable=True),
    sa.Column('mobile_hash', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('static_ability_score', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('edu_level', sa.INTEGER(), nullable=True),
    sa.Column('school_level', sa.INTEGER(), nullable=True),
    sa.Column('work_years', sa.INTEGER(), nullable=True),
    sa.Column('big_company_flag', sa.INTEGER(), nullable=False),
    sa.Column('cert_count', sa.INTEGER(), nullable=False),
    sa.Column('source_channel', sa.VARCHAR(length=32), nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('black_flag', sa.INTEGER(), nullable=False),
    sa.Column('black_type', sa.INTEGER(), nullable=True),
    sa.Column('black_add_at', sa.DATETIME(), nullable=True),
    sa.Column('note', sa.VARCHAR(length=512), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_no'),
    sa.UniqueConstraint('mobile_hash')
    )
    op.create_table('t_hr_candidate_tag_rel',
    sa.Column('candidate_id', sa.BIGINT(), nullable=False),
    sa.Column('tag_id', sa.BIGINT(), nullable=False),
    sa.Column('tag_source', sa.INTEGER(), nullable=False),
    sa.Column('valid_end', sa.DATE(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_hr_interview_slot',
    sa.Column('interviewer_id', sa.BIGINT(), nullable=False),
    sa.Column('demand_id', sa.BIGINT(), nullable=True),
    sa.Column('start_dt', sa.DATETIME(), nullable=False),
    sa.Column('end_dt', sa.DATETIME(), nullable=False),
    sa.Column('is_booked', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_hr_recruit_channel',
    sa.Column('channel_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('channel_type', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_hr_tag_dict',
    sa.Column('tag_code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('tag_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('tag_category', sa.VARCHAR(length=32), nullable=False),
    sa.Column('tag_sub_category', sa.VARCHAR(length=32), nullable=True),
    sa.Column('match_weight', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('support_target', sa.INTEGER(), nullable=False),
    sa.Column('sort_num', sa.INTEGER(), nullable=False),
    sa.Column('remark', sa.VARCHAR(length=512), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_code')
    )
    op.create_table('t_hr_entry',
    sa.Column('entry_no', sa.VARCHAR(length=32), nullable=False),
    sa.Column('event_id', sa.BIGINT(), nullable=False),
    sa.Column('resume_id', sa.BIGINT(), nullable=False),
    sa.Column('dept_id', sa.BIGINT(), nullable=False),
    sa.Column('position_id', sa.BIGINT(), nullable=False),
    sa.Column('entry_date', sa.DATE(), nullable=False),
    sa.Column('checklist_json', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_no')
    )
    op.create_table('t_hr_hire_event',
    sa.Column('event_no', sa.VARCHAR(length=32), nullable=False),
    sa.Column('process_id', sa.BIGINT(), nullable=True),
    sa.Column('employee_id', sa.BIGINT(), nullable=True),
    sa.Column('offer_id', sa.BIGINT(), nullable=True),
    sa.Column('hire_type', sa.INTEGER(), nullable=False),
    sa.Column('event_status', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_no')
    )
    op.create_table('t_hr_demand_approval',
    sa.Column('demand_id', sa.BIGINT(), nullable=False),
    sa.Column('approve_user_id', sa.BIGINT(), nullable=True),
    sa.Column('approve_level', sa.INTEGER(), nullable=True),
    sa.Column('approve_result', sa.INTEGER(), nullable=False),
    sa.Column('approve_opinion', sa.VARCHAR(length=512), nullable=True),
    sa.Column('approve_time', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_hr_search_log',
    sa.Column('demand_id', sa.BIGINT(), nullable=False),
    sa.Column('search_type', sa.INTEGER(), nullable=False),
    sa.Column('search_at', sa.DATETIME(), nullable=False),
    sa.Column('match_total', sa.INTEGER(), nullable=False),
    sa.Column('remark', sa.VARCHAR(length=512), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_hr_interview_book',
    sa.Column('demand_id', sa.BIGINT(), nullable=False),
    sa.Column('resume_id', sa.BIGINT(), nullable=False),
    sa.Column('process_id', sa.BIGINT(), nullable=False),
    sa.Column('slot_id', sa.BIGINT(), nullable=False),
    sa.Column('interview_round', sa.INTEGER(), nullable=False),
    sa.Column('interview_type', sa.INTEGER(), nullable=False),
    sa.Column('meeting_code', sa.VARCHAR(length=32), nullable=True),
    sa.Column('meeting_pwd', sa.VARCHAR(length=16), nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('book_time', sa.DATETIME(), nullable=False),
    sa.Column('invite_json', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_hr_employee',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('dept_id', sa.BIGINT(), nullable=True),
    sa.Column('position_id', sa.BIGINT(), nullable=True),
    sa.Column('work_years', sa.INTEGER(), nullable=True),
    sa.Column('perf_score', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('last_promote_date', sa.DATE(), nullable=True),
    sa.Column('can_transfer', sa.INTEGER(), nullable=False),
    sa.Column('compositive_score', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('transfer_restrict_reason', sa.VARCHAR(length=256), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('t_hr_offer',
    sa.Column('offer_no', sa.VARCHAR(length=32), nullable=False),
    sa.Column('resume_id', sa.BIGINT(), nullable=False),
    sa.Column('process_id', sa.BIGINT(), nullable=False),
    sa.Column('demand_id', sa.BIGINT(), nullable=False),
    sa.Column('last_interview_id', sa.BIGINT(), nullable=True),
    sa.Column('offer_content', sa.TEXT(), nullable=True),
    sa.Column('salary_json', sqlite.JSON(), nullable=True),
    sa.Column('valid_deadline', sa.DATETIME(), nullable=False),
    sa.Column('offer_status', sa.INTEGER(), nullable=False),
    sa.Column('send_user_id', sa.BIGINT(), nullable=False),
    sa.Column('send_time', sa.DATETIME(), nullable=False),
    sa.Column('offer_file_id', sa.BIGINT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_no')
    )
    op.create_table('t_hr_resume',
    sa.Column('candidate_id', sa.BIGINT(), nullable=False),
    sa.Column('resume_file_id', sa.BIGINT(), nullable=True),
    sa.Column('storage_time', sa.DATETIME(), nullable=False),
    sa.Column('base_score', sa.DECIMAL(precision=4, scale=1), nullable=False),
    sa.Column('work_exp_text', sa.TEXT(), nullable=True),
    sa.Column('extract_json', sqlite.JSON(), nullable=True),
    sa.Column('touch_json', sqlite.JSON(), nullable=True),
    sa.Column('source_channel_id', sa.BIGINT(), nullable=True),
    sa.Column('mail_account_id', sa.BIGINT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_hr_recruit_demand',
    sa.Column('demand_no', sa.VARCHAR(length=32), nullable=False),
    sa.Column('dept_id', sa.BIGINT(), nullable=False),
    sa.Column('position_id', sa.BIGINT(), nullable=False),
    sa.Column('recruit_type', sa.INTEGER(), nullable=False),
    sa.Column('plan_headcount', sa.INTEGER(), nullable=False),
    sa.Column('filled_count', sa.INTEGER(), nullable=False),
    sa.Column('expect_entry_date', sa.DATE(), nullable=True),
    sa.Column('jd_content', sa.TEXT(), nullable=True),
    sa.Column('edu_min', sa.VARCHAR(length=64), nullable=True),
    sa.Column('exp_min', sa.INTEGER(), nullable=True),
    sa.Column('work_city', sa.VARCHAR(length=64), nullable=True),
    sa.Column('publishing_channels', sqlite.JSON(), nullable=True),
    sa.Column('demand_status', sa.INTEGER(), nullable=False),
    sa.Column('cancel_at', sa.DATETIME(), nullable=True),
    sa.Column('cancel_reason', sa.VARCHAR(length=512), nullable=True),
    sa.Column('audit_flow', sqlite.JSON(), nullable=True),
    sa.Column('headcount_reserve_json', sqlite.JSON(), nullable=True),
    sa.Column('creator_id', sa.BIGINT(), nullable=False),
    sa.Column('hr_owner_id', sa.BIGINT(), nullable=True),
    sa.Column('internal_searched', sa.INTEGER(), nullable=False),
    sa.Column('resume_searched', sa.INTEGER(), nullable=False),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.Column('is_internal_given_up', sa.INTEGER(), nullable=False),
    sa.Column('recommend_limit', sa.INTEGER(), nullable=True),
    sa.Column('salary_range', sa.VARCHAR(length=64), nullable=True),
    sa.Column('urgency', sa.VARCHAR(length=16), nullable=False),
    sa.Column('required_skills', sqlite.JSON(), nullable=True),
    sa.Column('plus_skills', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('demand_no')
    )
    op.create_table('t_hr_internal_match_log',
    sa.Column('match_no', sa.VARCHAR(length=32), nullable=False),
    sa.Column('demand_id', sa.BIGINT(), nullable=False),
    sa.Column('employee_id', sa.BIGINT(), nullable=False),
    sa.Column('match_score', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('match_status', sa.INTEGER(), nullable=False),
    sa.Column('operator_user_id', sa.BIGINT(), nullable=True),
    sa.Column('matched_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_no')
    )
    op.create_table('t_hr_score_rule',
    sa.Column('score_scene', sa.INTEGER(), nullable=False),
    sa.Column('weight_json', sqlite.JSON(), nullable=False),
    sa.Column('pool_min_score', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('auto_invite_min_score', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('file_name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=512), nullable=False),
    sa.Column('file_extension', sa.VARCHAR(length=16), nullable=True),
    sa.Column('file_size', sa.BIGINT(), nullable=True),
    sa.Column('biz_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_hr_employee_tag_rel',
    sa.Column('employee_id', sa.BIGINT(), nullable=False),
    sa.Column('tag_id', sa.BIGINT(), nullable=False),
    sa.Column('tag_source', sa.INTEGER(), nullable=False),
    sa.Column('tag_related_score', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('valid_end', sa.DATE(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_core_position',
    sa.Column('position_id', sa.BIGINT(), nullable=False),
    sa.Column('position_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dept_id', sa.BIGINT(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_hr_recruit_process',
    sa.Column('process_no', sa.VARCHAR(length=32), nullable=False),
    sa.Column('demand_id', sa.BIGINT(), nullable=False),
    sa.Column('resume_id', sa.BIGINT(), nullable=False),
    sa.Column('candidate_id', sa.BIGINT(), nullable=False),
    sa.Column('process_status', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_no')
    )
    op.create_table('t_core_user',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('real_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('dept_id', sa.BIGINT(), nullable=True),
    sa.Column('position_id', sa.BIGINT(), nullable=True),
    sa.Column('role_code', sa.VARCHAR(length=32), nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
    sa.Column('mobile', sa.VARCHAR(length=20), nullable=True),
    sa.Column('feishu_open_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_hr_resume_match',
    sa.Column('resume_id', sa.BIGINT(), nullable=False),
    sa.Column('demand_id', sa.BIGINT(), nullable=False),
    sa.Column('match_score', sa.DECIMAL(precision=4, scale=1), nullable=False),
    sa.Column('score_detail', sqlite.JSON(), nullable=True),
    sa.Column('calculate_time', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_hr_interview_record',
    sa.Column('book_id', sa.BIGINT(), nullable=False),
    sa.Column('process_id', sa.BIGINT(), nullable=False),
    sa.Column('interviewer_ids', sqlite.JSON(), nullable=False),
    sa.Column('submit_interviewer_id', sa.BIGINT(), nullable=False),
    sa.Column('is_arrive', sa.INTEGER(), nullable=False),
    sa.Column('interview_result', sa.INTEGER(), nullable=False),
    sa.Column('evaluate_text', sa.TEXT(), nullable=True),
    sa.Column('score_json', sqlite.JSON(), nullable=True),
    sa.Column('audio_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('feishu_memo_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('highlight_json', sqlite.JSON(), nullable=True),
    sa.Column('ai_draft_json', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_hr_recruit_mail_account',
    sa.Column('account_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email_address', sa.VARCHAR(length=128), nullable=False),
    sa.Column('imap_host', sa.VARCHAR(length=128), nullable=True),
    sa.Column('imap_port', sa.INTEGER(), nullable=True),
    sa.Column('owner_user_id', sa.BIGINT(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=False),
    sa.Column('monitor_folder', sa.VARCHAR(length=128), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('t_hr_dept_hc',
    sa.Column('dept_id', sa.BIGINT(), nullable=False),
    sa.Column('plan_year', sa.INTEGER(), nullable=False),
    sa.Column('total_headcount', sa.INTEGER(), nullable=False),
    sa.Column('used_headcount', sa.INTEGER(), nullable=False),
    sa.Column('available_headcount', sa.INTEGER(), nullable=False),
    sa.Column('operation_json', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_core_dept',
    sa.Column('dept_id', sa.BIGINT(), nullable=False),
    sa.Column('dept_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('parent_dept_id', sa.BIGINT(), nullable=True),
    sa.Column('dept_path', sa.VARCHAR(length=512), nullable=True),
    sa.Column('sort_num', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_hr_chat_log',
    sa.Column('resume_id', sa.BIGINT(), nullable=True),
    sa.Column('demand_id', sa.BIGINT(), nullable=True),
    sa.Column('chat_type', sa.INTEGER(), nullable=False),
    sa.Column('chat_content', sa.TEXT(), nullable=False),
    sa.Column('operate_time', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_hr_chat_log')
    op.drop_table('t_core_dept')
    op.drop_table('t_hr_dept_hc')
    op.drop_table('t_hr_recruit_mail_account')
    op.drop_table('t_hr_interview_record')
    op.drop_table('t_hr_resume_match')
    op.drop_table('t_core_user')
    op.drop_table('t_hr_recruit_process')
    op.drop_table('t_core_position')
    op.drop_table('t_hr_employee_tag_rel')
    op.drop_table('files')
    op.drop_table('t_hr_score_rule')
    op.drop_table('t_hr_internal_match_log')
    op.drop_table('t_hr_recruit_demand')
    op.drop_table('t_hr_resume')
    op.drop_table('t_hr_offer')
    op.drop_table('t_hr_employee')
    op.drop_table('t_hr_interview_book')
    op.drop_table('t_hr_search_log')
    op.drop_table('t_hr_demand_approval')
    op.drop_table('t_hr_hire_event')
    op.drop_table('t_hr_entry')
    op.drop_table('t_hr_tag_dict')
    op.drop_table('t_hr_recruit_channel')
    op.drop_table('t_hr_interview_slot')
    op.drop_table('t_hr_candidate_tag_rel')
    op.drop_table('t_hr_candidate')
    # ### end Alembic commands ###
